<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sm="http://www.sitemaps.org/schemas/sitemap/0.9">
  <xsl:output method="html" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <title>Sitemap</title>
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: #0f0f13; color: #e2e8f0; padding: 2rem 1rem; }
          .container { max-width: 900px; margin: 0 auto; }
          header { margin-bottom: 2rem; }
          header h1 { font-size: 1.5rem; font-weight: 700; color: #fff; margin-bottom: 0.25rem; }
          header p { font-size: 0.875rem; color: #94a3b8; }
          .badge { display: inline-block; background: #7c3aed22; color: #a78bfa; border: 1px solid #7c3aed44; border-radius: 999px; font-size: 0.75rem; font-weight: 600; padding: 0.2rem 0.75rem; margin-left: 0.5rem; vertical-align: middle; }
          table { width: 100%; border-collapse: collapse; background: #16161f; border-radius: 0.75rem; overflow: hidden; border: 1px solid #1e1e2e; }
          thead tr { background: #1a1a27; }
          th { text-align: left; padding: 0.875rem 1rem; font-size: 0.75rem; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 1px solid #1e1e2e; }
          td { padding: 0.75rem 1rem; font-size: 0.875rem; border-bottom: 1px solid #1a1a27; vertical-align: middle; }
          tr:last-child td { border-bottom: none; }
          tr:hover td { background: #1a1a27; }
          a { color: #a78bfa; text-decoration: none; word-break: break-all; }
          a:hover { color: #c4b5fd; text-decoration: underline; }
          .priority { display: inline-block; padding: 0.2rem 0.5rem; border-radius: 0.375rem; font-size: 0.75rem; font-weight: 600; }
          .p-high   { background: #10b98122; color: #34d399; }
          .p-mid    { background: #3b82f622; color: #60a5fa; }
          .p-low    { background: #64748b22; color: #94a3b8; }
          .date     { color: #64748b; font-size: 0.8rem; white-space: nowrap; }
          .freq     { color: #64748b; font-size: 0.8rem; }
          footer { margin-top: 1.5rem; text-align: center; font-size: 0.75rem; color: #475569; }
        </style>
      </head>
      <body>
        <div class="container">
          <header>
            <h1>XML Sitemap <span class="badge"><xsl:value-of select="count(sm:urlset/sm:url)"/> URLs</span></h1>
            <p>This sitemap is used by search engines to discover and index pages on this site.</p>
          </header>
          <table>
            <thead>
              <tr>
                <th>URL</th>
                <th>Last Modified</th>
                <th>Change Freq</th>
                <th>Priority</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sm:urlset/sm:url">
                <tr>
                  <td><a href="{sm:loc}"><xsl:value-of select="sm:loc"/></a></td>
                  <td class="date">
                    <xsl:choose>
                      <xsl:when test="sm:lastmod"><xsl:value-of select="substring(sm:lastmod, 1, 10)"/></xsl:when>
                      <xsl:otherwise>—</xsl:otherwise>
                    </xsl:choose>
                  </td>
                  <td class="freq"><xsl:value-of select="sm:changefreq"/></td>
                  <td>
                    <xsl:variable name="p" select="sm:priority"/>
                    <xsl:choose>
                      <xsl:when test="$p >= 0.8"><span class="priority p-high"><xsl:value-of select="$p"/></span></xsl:when>
                      <xsl:when test="$p >= 0.5"><span class="priority p-mid"><xsl:value-of select="$p"/></span></xsl:when>
                      <xsl:otherwise><span class="priority p-low"><xsl:value-of select="$p"/></span></xsl:otherwise>
                    </xsl:choose>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
          <footer>Generated by VoltexaHub</footer>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
